### ISSUE TITLE
Write up specification for CSVV files

### ISSUE THREAD

**Issue by jrising** [ClimateImpactLab/gcp-tasks#10]

**Comment by jrising** [comment]
Now written up.  Need to get feedback.

https://docs.google.com/document/d/1V7Wc4r-sgREwl70bAHv19tUrA6DS-w8IAPUMTS3Sy_8/edit

**Comment by delgadom** [comment]
Can the RAs write netCDF files? Files with multiple variables seem like they could be written to netCDFs much more easily...

**Comment by jrising** [comment]
Only some of them.  I've been getting push-back on NetCDFs, with people asking me to convert them to csvs.  :-P

**Comment by delgadom** [comment]
Haha. The struggle is real 😜

**Comment by jrising** [comment]
This is de facto agreed upon, so I'm going to close it.
