### ISSUE TITLE
Hide "permissions error" messages in Aggregation script

### ISSUE THREAD

**Issue by jrising** [ClimateImpactLab/gcp-tasks#15]
After aggregating a directory, the code currently tries to change all files to be readable by others in the group.  However, if there are already other people's files in the folder, it produces a lot of messages.  We should hide those messages.

**Comment by delgadom** [comment]
@jrising is this a bash script? I have a "publish" script that could be helpful here... 

```
! /usr/bin/bash

chgrp -Rf co_laika /global/scratch/groups/co_laika && chmod -Rf 770 /global/scratch/groups/co_laika
```

**Comment by jrising** [comment]
Sorry, it's in python.
