### ISSUE TITLE
Build AWS management into osdc_server, and upload some stuff there

### ISSUE THREAD

**Issue by jrising** [ClimateImpactLab/gcp-tasks#3]
It will look good to Chicago if we're using this resource.

**Comment by jgerardsimcock** [comment]
What are you thinking in terms of AWS management here? Is osdc_server a server class in a new python module? We are planning on using the s3 storage on chicago. If this is what you are describing, I'd love to hear your thoughts on what you are thinking.

**Comment by jrising** [comment]
`osdc_server` is a class derived from `paramiko_server` from `computer` and used for interacting with OSDC.  I would love for Jong-Kai to merge in his version of the class (the current one is just in `impact-calculations`), but it looks like he isn't on here.  But the principle is this: we should have a consistent API that allows us to upload files to any storage option.  Within `computer`, that is by using the `push_disk` function.

So the tasks I was imagining were to make a `push_disk` function that sends files to AWS, and then send a bunch of our results there.
